Env: "local"
serverCfg:
  ListedAddr: ":8008"
  DefaultWriteTimeOut: 15

linkStoreCfg:
  WalFilePath: "./backup/links.log"
  WalFileBufferSize: 50
  WalFileWriteDuraction: 60
  LinkStoreBackup: "./backup/links.json"
  LinkStorageBackupDuration: 1,800